# Generated by Django 6.0.2 on 2026-02-21 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Administrator', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_employee',
            name='department',
        ),
        migrations.RemoveField(
            model_name='tbl_employee',
            name='designation',
        ),
        migrations.DeleteModel(
            name='tbl_department',
        ),
        migrations.DeleteModel(
            name='tbl_designation',
        ),
        migrations.DeleteModel(
            name='tbl_employee',
        ),
    ]
