# Generated by Django 6.0.2 on 2026-02-21 16:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Administrator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_electrician',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('electrician_name', models.CharField(max_length=30)),
                ('electrician_email', models.CharField(max_length=30)),
                ('electrician_contact', models.CharField(max_length=30)),
                ('electrician_address', models.CharField(max_length=30)),
                ('electrician_photo', models.FileField(upload_to='Assets/Electrician/photo/')),
                ('electrician_aadhar', models.FileField(null=True, upload_to='Assets/Electrician/aadhar/')),
                ('electrician_pcc', models.FileField(null=True, upload_to='Assets/Electrician/pcc/')),
                ('electrician_password', models.CharField(max_length=30)),
                ('electrician_status', models.IntegerField(default=0)),
                ('local_place', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Administrator.tbl_local_place')),
                ('work_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Administrator.tbl_work_category')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller_name', models.CharField(max_length=30)),
                ('seller_email', models.CharField(max_length=30)),
                ('seller_contact', models.CharField(max_length=30)),
                ('seller_address', models.CharField(max_length=30)),
                ('seller_logo', models.FileField(upload_to='Assets/Seller/logo/')),
                ('seller_proof', models.FileField(upload_to='Assets/Seller/proof/')),
                ('seller_password', models.CharField(max_length=30)),
                ('seller_status', models.IntegerField(default=0)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Administrator.tbl_place')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=30)),
                ('user_email', models.CharField(max_length=30)),
                ('user_contact', models.CharField(max_length=30)),
                ('user_address', models.CharField(max_length=30)),
                ('user_photo', models.FileField(upload_to='Assets/User/photo/')),
                ('user_password', models.CharField(max_length=30)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Administrator.tbl_place')),
            ],
        ),
    ]
