# Generated by Django 6.0.1 on 2026-03-08 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_tbl_electrician_gallery_tbl_electrician_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_work_booking',
            name='work_file',
            field=models.FileField(blank=True, null=True, upload_to='Assets/WorkBookings/'),
        ),
        migrations.AddField(
            model_name='tbl_work_booking',
            name='work_location',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
