# Generated by Django 6.0.1 on 2026-03-08 16:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0001_initial'),
        ('Seller', '0001_initial'),
        ('User', '0003_tbl_work_booking_work_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_complaint',
            name='complaint_type',
            field=models.IntegerField(choices=[(1, 'Product'), (2, 'Electrician'), (3, 'Site')], default=1),
        ),
        migrations.AddField(
            model_name='tbl_complaint',
            name='electrician',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_electrician'),
        ),
        migrations.AddField(
            model_name='tbl_complaint',
            name='seller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_seller'),
        ),
        migrations.AlterField(
            model_name='tbl_complaint',
            name='complaint_content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='tbl_complaint',
            name='complaint_reply',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tbl_complaint',
            name='complaint_replydate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tbl_complaint',
            name='complaint_title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='tbl_complaint',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Seller.tbl_product'),
        ),
    ]
