# Generated by Django 6.0.1 on 2026-03-14 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0004_tbl_complaint_complaint_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_complaint',
            name='user_solved',
            field=models.BooleanField(default=False),
        ),
    ]
